openapi: 3.1.0
info:
  title: Task API
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: local development servers
  - url: https://task-api-psxy.onrender.com
    description: Live server
tags:
  - name: Tasks
    description: Task related endpoints
paths:
  /tasks:
    get:
      summary: List all tasks
      tags:
        - Tasks
      parameters:
        - name: completed
          in: query
          requied: false
          description: Filter tasks by completion status
          schema:
            type: boolean
            example: true
        - name: limit
          in: query
          required: false
          description: maximum number of tasks to return
          schema:
            type: integer
            example: 10
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    getById:
      summary: Get post by id
      tags:
        - Tasks
      parameters:
        name: id
        in: url
        required: true
        description: Search for task by Id number
        schema:
          type: integer
          example: 1
      responses:
        '200':
          description: Task found successfully
          content:
            application/json:
              schema:
                $ref: ../components/schemas/Task.yaml
        '400':
          $ref: ../components/responses/BadRequest.yaml
        '404':
          description: Task Not found
          content:
            application/json:
              schema:
                $ref: ../components/responses/InvalidInput.yaml
    post:
      summary: Create a new task
      tags:
        - Tasks
      requestBody:
        required: true
        content:
          application/json:
            schemas:
              $ref: ../components/schemas/Task.yaml
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          $ref: '#/components/responses/BadRequest'
  /tasks/id:
    get:
      summary: Get post by id
      tags:
        - Tasks
      parameters:
        name: id
        in: url
        required: true
        description: Search for task by Id number
        schema:
          type: integer
          example: 1
      responses:
        '200':
          description: Task found successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/InvalidInput'
components:
  schemas:
    Task:
      type: object
      properties:
        id:
          readOnly: true
          type: integer
          example: 1
        title:
          tpye: string
          example: Buy groceries
        completed:
          type: boolean
          example: false
    ValidationError:
      type: object
      properties:
        error:
          type: string
          example: Validation failed
        details:
          type: array
          items:
            type: string
    NotNumber:
      type: object
      properties:
        error:
          type: string
          example: Task not found
        details:
          type: array
          items:
            type: string
  responses:
    BadRequest:
      description: Invalid input
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ValidationError'
    InvalidInput:
      description: Invalid input
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/NotNumber'
