openapi: 3.1.0
info:
  title: Task API
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: local development servers
  - url: https://task-api-psxy.onrender.com
    description: Live server 
  
tags:
  - name: Tasks
    description: Task related endpoints
paths:
  /tasks:
    $ref: paths/tasks.yaml
